set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g mouse on
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set-option -g set-titles on
set-option -g set-titles-string '#S'

bind C {
	splitw -f -l30% ''
	set-hook -p pane-mode-changed 'if -F "#{!=:#{pane_mode},copy-mode}" "kill-pane"'
	copy-mode -s'{last}'
}
