#!/usr/bin/env zsh

#
#
# Sets Prezto options.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# General
#

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':prezto:*:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':prezto:*:*' color 'yes'

# Set the Zsh modules to load (man zshmodules).
zstyle ':prezto:load' zmodule 'attr' 'stat'

# Set the Zsh functions to load (man zshcontrib).
zstyle ':prezto:load' zfunction 'zargs' 'zmv'

# Set the Prezto modules to load (browse modules).
# The order matters.

zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'directory' \
  'spectrum' \
  'utility' \
  'archive' \
  'git' \
  'osx' \
  'completion' \
  'syntax-highlighting' \
  'history-substring-search' \
  'autosuggestions' \
  'contrib-prompt' \
  'prompt' \
  'history' \
  'tmux' \
  'ssh' \
  'fzf-tab' \
  'fzf-tab-source'

#
# Completion
#

zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 -a --color=always $realpath'
zstyle ':fzf-tab:complete:*:*' fzf-preview 'less ${(Q)realpath}'
# zstyle ':fzf-tab:complete:*:options' fzf-preview
# zstyle ':fzf-tab:complete:*:argument-1' fzf-preview
zstyle ':fzf-tab:complete:(-command-|-parameter-|-brace-parameter-|export|unset|expand):*' fzf-preview 'echo ${(P)word}'

zstyle ':fzf-tab:complete:git-(add|diff|restore):*' fzf-preview \
	'git diff $word | delta'
zstyle ':fzf-tab:complete:git-(log|lg):*' fzf-preview \
	'git log --color=always $word'
zstyle ':fzf-tab:complete:git-help:*' fzf-preview \
	'git help $word | bat -plman --color=always'
zstyle ':fzf-tab:complete:git-show:*' fzf-preview \
	'case "$group" in
	"commit tag") git show --color=always $word ;;
	*) git show --color=always $word | delta ;;
	esac'
zstyle ':fzf-tab:complete:git-(checkout|co):*' fzf-preview \
	'case "$group" in
	"modified file") git diff $word | delta ;;
	"recent commit object name") git show --color=always $word | delta ;;
	*) git log --color=always $word ;;
	esac'

zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':fzf-tab:*' prefix ' '
zstyle ':fzf-tab:*' fzf-flags --bind=shift-alt-up:preview-half-page-up,shift-alt-down:preview-half-page-down --preview-window=wrap
zstyle ':fzf-tab:*' popup-min-size 50 8
zstyle ':fzf-tab:*' show-group 'full'
zstyle ':fzf-tab:*' single-group color header

#
# Editor
#

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':prezto:module:editor' key-bindings 'emacs'

# Auto convert .... to ../..
zstyle ':prezto:module:editor' dot-expansion 'yes'

#
# Git
#

# Ignore submodules when they are 'dirty', 'untracked', 'all', or 'none'.
# zstyle ':prezto:module:git:status:ignore' submodules 'all'
zstyle ':prezto:module:git:alias' skip 'yes'

#
# GNU Utility
#

# Set the command prefix on non-GNU systems.
# zstyle ':prezto:module:gnu-utility' prefix 'g'

#
# History
#

zstyle ':prezto:module:history' BANG_HIST 'yes'
zstyle ':prezto:module:history' SHARE_HISTORY 'no'
zstyle ':prezto:module:history' EXTENDED_HISTORY 'yes'
zstyle ':prezto:module:history' HIST_REDUCE_BLANKS 'yes'
zstyle ':prezto:module:history' HIST_VERIFY 'yes'
zstyle ':prezto:module:history' COMPLETE_ALIASES 'yes'
zstyle ':prezto:module:history' INC_APPEND_HISTORY 'no'
zstyle ':prezto:module:history' HIST_EXPIRE_DUPS_FIRST 'yes'
zstyle ':prezto:module:history' HIST_IGNORE_DUPS 'yes'
zstyle ':prezto:module:history' HIST_IGNORE_ALL_DUPS 'yes'
zstyle ':prezto:module:history' HIST_IGNORE_SPACE 'yes'
zstyle ':prezto:module:history' HIST_SAVE_NO_DUPS 'yes'
zstyle ':prezto:module:history' HIST_FIND_NO_DUPS 'yes'
zstyle ':prezto:module:history' HIST_BEEP 'no'
zstyle ':prezto:module:history' HIST_REDUCE_BLANKS 'yes'
zstyle ':prezto:module:history' HISTSIZE 10000
zstyle ':prezto:module:history' SAVEHIST 500000

#
# History Substring Search
#

# Set the query found color.
# zstyle ':prezto:module:history-substring-search:color' found ''

# Set the query not found color.
# zstyle ':prezto:module:history-substring-search:color' not-found ''

# Set the search globbing flags.
# zstyle ':prezto:module:history-substring-search' globbing-flags ''

zstyle ':prezto:module:autosuggestions' color 'yes'
# zstyle ':prezto:module:autosuggestions:color' found ''

#
# Pacman
#

# Set the Pacman frontend.
# zstyle ':prezto:module:pacman' frontend 'yaourt'

#
# Prompt
#

# Set the prompt theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
# zstyle ':prezto:module:prompt' theme 'skwp'
zstyle ':prezto:module:prompt' theme 'spaceship'

#
# Ruby
#

# Auto switch the Ruby version on directory change.
# zstyle ':prezto:module:ruby:chruby' auto-switch 'yes'

#
# Screen
#

# Auto start a session when Zsh is launched in a local terminal.
# zstyle ':prezto:module:screen:auto-start' local 'yes'

# Auto start a session when Zsh is launched in a SSH connection.
# zstyle ':prezto:module:screen:auto-start' remote 'yes'

#
# SSH
#

# Enable ssh-agent forwarding.
zstyle ':prezto:module:ssh-agent' forwarding 'yes'

# Set the SSH identities to load into the agent.
zstyle ':prezto:module:ssh:load' identities 'id_rsa' 'id_ed25519'

#
# Syntax Highlighting
#

# Set syntax highlighters.
# By default, only the main highlighter is enabled.
zstyle ':prezto:module:syntax-highlighting' highlighters \
  'main' \
  'brackets' \
  'pattern' \
  'line' \
  'cursor' \
  'root'
#
# Set syntax highlighting styles.
# zstyle ':prezto:module:syntax-highlighting' styles \
#   'builtin' 'bg=blue' \
#   'command' 'bg=blue' \
#   'function' 'bg=blue'

#
# Terminal
#

# Auto set the tab and window titles.
zstyle ':prezto:module:terminal' auto-title 'yes'

# Set the window title format.
zstyle ':prezto:module:terminal:window-title' format '%n@%m: %s'

# Set the tab title format.
zstyle ':prezto:module:terminal:tab-title' format '%m: %s'

#
# Tmux
#

# Auto start a session when Zsh is launched in a local terminal.
# zstyle ':prezto:module:tmux:auto-start' local 'yes'

# Auto start a session when Zsh is launched in a SSH connection.
zstyle ':prezto:module:tmux:auto-start' remote 'no'

# Integrate with iTerm2.
zstyle ':prezto:module:tmux:iterm' integrate 'yes'
