#!/usr/bin/env zsh

if (( EUID == 0 )) && command -v dpkg-query >/dev/null 2>&1 && ! dpkg-query -p eza >/dev/null 2>&1; then
    apt update
    apt install -y gpg

    mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | tee /etc/apt/sources.list.d/gierens.list
    chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    apt update
fi
